pipeline {

    agent { node { label 'prod' } }
    
    stages {


        stage('Build image Ms Note') {
            
            steps { 
            dir ('projet') {
                 sh ' sudo docker build -t mssolutionsback . && docker run --name dotnetexample -p 8081:80 -d mssolutionsback'
               
                         }
                      

			   
     
            }
        }
}


   
   
}