pipeline {

    agent { node { label 'prod' } }
    
    stages {


        stage('Build image Ms Note') {
            
            steps { 
            dir ('ProjetBack') {
                 sh ' sudo docker build -t mssolutionsback .'
               
                         }
                      

			   
     
            }
        }
}


   
   
}