pipeline {

    agent { node { label 'prod' } }
    
    stages {


        stage('Build image Ms Note') {
            
            steps { 
            dir ('MSNote') {
                 sh 'dotnet publish -c Release && sudo docker build -t mssolutionsback && docker run --name dotnetexample -p 8081:80 -d mssolutionsback'
               
                         }
                      

			   
     
            }
        }
}


   
   
}